name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  mycontext:
    name: My Context
    runs-on: ubuntu-latest
    steps:
      - name: My Context
        run: |
          # Print the event name
          # github.event_name - The name of the event that triggered the workflow run
          echo "github.event_name: ${{ github.event_name }}"
          # github.event.pull_request.number - The number of the pull request that triggered the workflow run
          echo "github.event.pull_request.number: ${{ github.event.pull_request.number }}"

  ci:
    name: CI
    # Do not run duplicate CI workflow on push event when it's a pull-request from the same repo i.e not a fork
    if: github.event_name != 'push' || (github.event.pull_request && github.event.pull_request.number == null)
    uses: emteknetnz/gha-ci/.github/workflows/ci.yml@main
