name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    # Do not run duplicate CI workflow on push event when it's a pull-request from the same repo i.e not a fork
    if: github.event_name != 'push' || (github.event.pull_request && github.event.pull_request.number == null)
    uses: emteknetnz/gha-ci/.github/workflows/ci.yml@main
