name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    # Do not run if is PR from same repo as this repo i.e. not a fork
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    uses: emteknetnz/gha-ci/.github/workflows/ci.yml@main
